ALTER TABLE bom_items ADD COLUMN lt VARCHAR(50) DEFAULT NULL;
ALTER TABLE bom_items ADD COLUMN moq DECIMAL(15,2) DEFAULT NULL;
ALTER TABLE po_items ADD COLUMN po_ref VARCHAR(100) DEFAULT NULL;
ALTER TABLE po_items ADD COLUMN thickness DECIMAL(15,2) DEFAULT NULL;
ALTER TABLE quotation_items ADD COLUMN moq DECIMAL(15,2) DEFAULT NULL;
ALTER TABLE delivery_note_items ADD COLUMN po_ref VARCHAR(100) DEFAULT NULL;
ALTER TABLE delivery_note_items ADD COLUMN thickness DECIMAL(15,2) DEFAULT NULL;
